language: go
sudo: false
go:
  - 1.13.1
env:
  - GO111MODULE=on
addons:
  apt:
    packages:
      rpm
install:
  - gem install fpm
  - npm install -g snyk
script:
  - make travis
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - snyk test
deploy:
  - provider: packagecloud
    username: AlexAkulov
    repository: hungryfox-unstable
    token: $PACKAGECLOUD_TOKEN
    package_glob: build/hungryfox-*.rpm
    dist: el/7
    skip_cleanup: true
  - provider: packagecloud
    username: AlexAkulov
    repository: hungryfox-unstable
    token: $PACKAGECLOUD_TOKEN
    package_glob: build/hungryfox_*.deb
    dist: debian/buster
    skip_cleanup: true
