#!/bin/sh
set -e

# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade

if ! getent group "hungryfox" > /dev/null 2>&1 ; then
    groupadd -r "hungryfox"
fi
if ! getent passwd "hungryfox" > /dev/null 2>&1 ; then
    useradd -r -g hungryfox -d /usr/share/hungryfox -s /sbin/nologin \
        -c "hungryfox" hungryfox
fi

if [ -x /bin/systemctl ] ; then
    /bin/systemctl daemon-reload
fi
